In [ ]:
# Imports
import pandas as pd
import numpy as np
import datetime as dt

In [96]:
# Read in the spending data
data = pd.read_csv("./experimental.csv")
data

           name           store  amount        date  tags
0  Cafe bustelo          Target    8.49  2026/05/11   NaN
1       Cascade          Target    5.99  2026/05/11   NaN
2     Groceries          Meijer  130.27  2026/04/25   NaN
3      Smoothie  Tous les Jours    6.89  2026/05/09   NaN

In [80]:
# Sum the total amount spent
amounts = data["amount"]
np.sum(amounts.to_numpy())

np.float64(151.64)

In [81]:
# Datetime
test_date_str = data["date"][0]
test_date = dt.datetime.strptime(test_date_str, "%Y/%m/%d")
test_date.year

2026

In [93]:
# Convert date strings in original dataframe into datetimes

dates_timestamp = []
for date in data["date"]:
    dates_timestamp.append(pd.Timestamp(date))

data["date"] = pd.Series(dates_timestamp)
data

           name           store  amount       date
0  Cafe bustelo          Target    8.49 2026-05-11
1       Cascade          Target    5.99 2026-05-11
2     Groceries          Meijer  130.27 2026-04-25
3      Smoothie  Tous les Jours    6.89 2026-05-09